### ISSUE TITLE
 Implement Agent-Based Workflow for Research Automation

### ISSUE THREAD

**Issue by Harshal292004** [Hackur45/automated-researching-method#1]
Develop an agent-driven workflow to enable the research agent to autonomously complete research tasks and streamline the entire process. This enhancement should focus on maximizing efficiency and reducing manual intervention by leveraging agent capabilities.

**Comment by Harshal292004** [comment]
Our aim  is to integrate llama-8b-instruct by Hugging Face with Retrieval-Augmented Generation (RAG) and memory components to enable follow-up questioning capabilities. Subsequently, we'll use agents to assign roles for formatting everything in LaTeX, allowing for seamless conversion to a research paper format.

**Comment by Hackur45** [comment]
Got Agents for the work flow and elimination of automated google search.
